export const SET_NUMBER = "SET_NUMBER";
export const CHANGE_CURRENT_NUMBER = "CHANGE_CURRENT_NUMBER";
export const DEL_NUMBER = "DEL_NUMBER";
export const COMPLETE_STATUS = "COMPLETE_STATUS";
export const IN_PROGRESS_STATUS = "IN_PROGRESS_STATUS";
